//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlaybuhEntities : DbContext
    {
        public PlaybuhEntities()
            : base("name=PlaybuhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contragent> Contragent { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Operation> Operation { get; set; }
        public virtual DbSet<SourceOperation> SourceOperation { get; set; }
        public virtual DbSet<SubsourceOperation> SubsourceOperation { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Taxrate> Taxrate { get; set; }
    }
}
