//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERATIONS
    {
        public int id { get; set; }
        public int id_subsource { get; set; }
        public DateTime operation_date { get; set; }
        public decimal revenue { get; set; }
        public int id_tax_rate { get; set; }
        public Nullable<decimal> earnings { get; set; }
        public Nullable<DateTime> create_date { get; set; }
        public int id_employee { get; set; }
        public int id_contragent { get; set; }
    
        public virtual CONTRAGENTS CONTRAGENTS { get; set; }
        public virtual EMPLOYEES EMPLOYEES { get; set; }
        public virtual SUBSOURCE_OPERATION SUBSOURCE_OPERATION { get; set; }
        public virtual TAXRATE TAXRATE { get; set; }
    }
}
