//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int id { get; set; }
        public System.DateTime operation_date { get; set; }
        public decimal revenue { get; set; }
        public Nullable<decimal> earnings { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    
        public virtual Contragent Contragent { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual SubsourceOperation SubsourceOperation { get; set; }
        public virtual Taxrate Taxrate { get; set; }
    }
}
