//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceOperation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SourceOperation(string sourceName, bool isRevenue, string description = null)
        {
            this.SubsourceOperation = new HashSet<SubsourceOperation>();
            source_name = sourceName;
            is_revenue = isRevenue;
            this.description = description;
        }
    
        public int id { get; set; }
        public string source_name { get; set; }
        public bool is_revenue { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubsourceOperation> SubsourceOperation { get; set; }
    }
}
