//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameBookkeeping.ServicePlaybuh {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePlaybuh.IServiceNetwork")]
    public interface IServiceNetwork {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNetwork/GetEmployees", ReplyAction="http://tempuri.org/IServiceNetwork/GetEmployeesResponse")]
        BLogic.Model.Employee[] GetEmployees(bool showArchive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNetwork/GetEmployees", ReplyAction="http://tempuri.org/IServiceNetwork/GetEmployeesResponse")]
        System.Threading.Tasks.Task<BLogic.Model.Employee[]> GetEmployeesAsync(bool showArchive);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceNetworkChannel : GameBookkeeping.ServicePlaybuh.IServiceNetwork, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceNetworkClient : System.ServiceModel.ClientBase<GameBookkeeping.ServicePlaybuh.IServiceNetwork>, GameBookkeeping.ServicePlaybuh.IServiceNetwork {
        
        public ServiceNetworkClient() {
        }
        
        public ServiceNetworkClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceNetworkClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNetworkClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNetworkClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BLogic.Model.Employee[] GetEmployees(bool showArchive) {
            return base.Channel.GetEmployees(showArchive);
        }
        
        public System.Threading.Tasks.Task<BLogic.Model.Employee[]> GetEmployeesAsync(bool showArchive) {
            return base.Channel.GetEmployeesAsync(showArchive);
        }
    }
}
